export const FETCH_ARTICLES_REQUEST = "FETCH_ARTICLES_REQUEST";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";

export const FETCH_EACH_ARTICLE_REQUEST = "FETCH_EACH_ARTICLE_REQUEST";
export const FETCH_EACH_ARTICLE_SUCCESS = "FETCH_EACH_ARTICLE_SUCCESS";
export const FETCH_EACH_ARTICLE_FAILURE = "FETCH_EACH_ARTICLE_FAILURE";
