export const FETCH_ARTICLES_REQUEST = "FETCH_ARTICLES_REQUEST";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";

export const FETCH_EACH_ARTICLE_REQUEST = "FETCH_EACH_ARTICLE_REQUEST";
export const FETCH_EACH_ARTICLE_SUCCESS = "FETCH_EACH_ARTICLE_SUCCESS";
export const FETCH_EACH_ARTICLE_FAILURE = "FETCH_EACH_ARTICLE_FAILURE";

export const FETCH_ALL_TOPICS_REQUEST = "FETCH_ALL_TOPICS_REQUEST";
export const FETCH_ALL_TOPICS_SUCCESS = "FETCH_ALL_TOPICS_SUCCESS";
export const FETCH_ALL_TOPICS_FAILURE = "FETCH_ALL_TOPICS_FAILURE";

export const FETCH_ARTICLES_BY_TOPIC_REQUEST =
  "FETCH_ARTICLES_BY_TOPIC_REQUEST";
export const FETCH_ARTICLES_BY_TOPIC_SUCCESS =
  "FETCH_ARTICLES_BY_TOPIC_SUCCESS";
export const FETCH_ARTICLES_BY_TOPIC_FAILURE =
  "FETCH_ARTICLES_BY_TOPIC_FAILURE";

export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";
